name: At the end of every day
on:
  schedule:
    - cron: "0 0 * * *"
  branches:
    - main
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Cypress Tests
        run: npx cypress run
