name: At the end of every day

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run
